include/boost/uuid/detail/uuid_x86.hpp
Upcoming clang-3.5 in c++11 mode issues "deprecated" warning for the "register" keyword. Just drop this.
=> Remove deprecated 'register' keyword

include/boost/uuid/seed_rng.hpp
... such as MinGW, with which g++ generates the following errors during building client code using boost::uuids::basic_random_generator:
> In file included from /foo/bar/include/boost/uuid/random_generator.hpp:12:0,
>                  from /foo/bar/include/boost/uuid/uuid_generators.hpp:17,
>                  from ../../../../src/uuidgen.h:8,
>                  from ../../../../src/baz/quux.cc:28:
> /foo/bar/include/boost/uuid/seed_rng.hpp:240:20: error: 'winapi' in namespace 'boost::detail' does not name a type
>      boost::detail::winapi::HCRYPTPROV_ random_;
>                     ^
> /foo/bar/include/boost/uuid/seed_rng.hpp: In constructor 'boost::uuids::detail::seed_rng::seed_rng()':
> /foo/bar/include/boost/uuid/seed_rng.hpp:89:11: error: class 'boost::uuids::detail::seed_rng' does …
=> fix for the non-MSVC case on Windows

include/boost/uuid/detail/config.hpp, include/boost/uuid/detail/uuid_x86.hpp
The pull request enables all SSE extensions when AVX is enabled with MSVC compiler switches. It also silences an MSVC warning.
=> Add a check for AVX in VS2013 and later

include/boost/uuid/uuid_io.hpp, test/test_io.cpp
The defect https://svn.boost.org/trac/boost/ticket/11385 reports a
situation where a uuid's single-hex-digit values are improperly padded
when std::left is set on the stream.
It is fixed by ensuring that the ostream overload always uses std::right
to be consistent with the default behavior.
=> Fixed padded output of UUID when std::left is set

test/test_wserialization.cpp
Fixed missing  ```boost::``` namespace
=> Fixed missing boost:: namespace

include/boost/uuid/seed_rng.hpp
With BOOST_NO_ANSI_APIS, there is no CryptAcquireContextA.
=> Fix compilation with BOOST_NO_ANSI_APIS

include/boost/uuid/seed_rng.hpp
Built under gcc-6.3 and Visual Studio 2017 - passed tests and no warnings.
=> 12971: fix compiler warning converting from NULL on Windows

include/boost/uuid/string_generator.hpp, test/test_string_generator.cpp, uuid.html
For example, "12b672ea-388d-47da-9c26-bec5bc8a06cb-foo" was not considered invalid before, but it is now.
=> Fix boost trac 8630, 9343, 11482, 11483, 12253 improving invalid string generator handling in uuid

test/Jamfile.v2, test/test_random_generator.cpp
Investigating Trac 12258 I found the random_device unit test was not enabled.  This establishes a formal dependency during the build of uuid on random, but that seems quite appropriate.  Tested on Windows (MSVC2015) and Linux (gcc-4.8, trusty).
=> 12258: re-enable unit test for random_device generator

.travis.yml, README.md, appveyor.yml, test/Jamfile.v2
Also includes an appveyor environment patch for boostorg/serialization
that allows it to build, which will be submitted back to that project.
The workflow to use this is to first fork uuid into your own github account and then follow the instructions located here:
https://svn.boost.org/trac10/wiki/TravisCoverals
Then when you make a code change, you first submit it as a pull request to your own fork's develop and then the Appveyor and Travis CI integration will kick in and build things!  Then when you are satisfied you can make another pull request against boostorg/uuid:develop and as long as it has the same commit ID, I believe that means it will also get the build status from the CI providers.  We'll see, this is all new territory for me.
I would vastly prefer it if pull requests going …
=> Add appveyor and travis pull request integration

.travis.yml, README.md, covscan.sh
I also converted the .travis.yml file from matrix to job processing, it's cleaner
=> enable coverity scan builds on develop merge into master

test/mock_random.cpp, test/mock_random.hpp
WINAPI macro definition in Boost.WinAPI is deprecated as it may clash with the macro defined in Windows SDK.
=> Switch WINAPI calling convention macros to the replacements from Boost.WinAPI

include/boost/uuid/detail/random_provider.hpp, include/boost/uuid/detail/random_provider_arc4random.ipp, include/boost/uuid/detail/random_provider_bcrypt.ipp, include/boost/uuid/detail/random_provider_getentropy.ipp, include/boost/uuid/detail/random_provider_posix.ipp, include/boost/uuid/detail/random_provider_wincrypt.ipp, include/boost/uuid/random_generator.hpp, test/Jamfile.v2, test/compile-fail/basic_random_generator_no_copy_assign.cpp, test/compile-fail/basic_random_generator_no_copy_ctor.cpp, test/compile-fail/random_generator_no_copy_assign.cpp, test/compile-fail/random_generator_no_copy_ctor.cpp, test/mock_random.hpp, test/test_generators.cpp, test/test_random_generator.cpp
The commit adds support for move constructors and assignment to random UUID
generators and random providers. Also, in POSIX random provider, the commit
improves handling of return value from ::read(), which returns -1
in case of error and may return 0 in case of success. Retry the call when
it was interrupted before reading any bytes from /dev/urandom.
Added new tests for movability.
This fixes #71
=> Add support for movability to random generators. Fix POSIX random provider

doc/uuid.html, include/boost/uuid/detail/random_provider_detect_platform.hpp, include/boost/uuid/detail/random_provider_getrandom.ipp, include/boost/uuid/detail/random_provider_include_platform.hpp, test/Jamfile.v2, test/mock_random.hpp
getrandom is the base implementation for getentropy on Linux. It is also
available in the form of a syscall, which can be called directly on systems with
glibc versions older than 2.25 which don't yet provide wrappers for getrandom or
getentropy but have a recent enough Linux kernel (for example, Debian Stretch).
On systems other than Linux (e.g. Solaris) getentropy is documented as a
source for initialization of a user-space PRNG instead of a direct source
for random data. Since we use the random data directly to initialize UUIDs,
using getrandom on other platforms, where available, would be more preferable
than getentropy. Unfortunately, the only other platform that is known to support
both getentropy and getrandom (Solaris) documents getrandom to return 0
on error, which is a valid …
=> Add support for Linux-specific getrandom call to obtain random data.

include/boost/uuid/detail/random_provider_detect_platform.hpp
Android supports getrandom and getentropy functions only since API version 28.
As part of the fix converted Linux/Android platform detection from Boost.Predef
to direct checks of platform-specific macros. This is to work around
Boost.Predef problem described in [1] - depending on header inclusion order
Boost.Predef may indicate Linux or Android. When that problem is fixed we
may change back to Boost.Predef.
Fixes https://github.com/boostorg/uuid/issues/76.
[1]: https://github.com/boostorg/predef/issues/81#issuecomment-413329061
=> Disable getrandom provider on Android prior to API version 28.

include/boost/uuid/basic_name_generator.hpp, include/boost/uuid/string_generator.hpp
This fixes -Wextra-semi and -Wmissing-noreturn. See individual commits for details.
=> Fix clang warnings

include/boost/uuid/detail/random_provider_bcrypt.ipp, include/boost/uuid/detail/random_provider_wincrypt.ipp
Avoid undefining BOOST_AUTO_LINK_NOMANGLE if it was previously defined.
Maybe better solution would be to directly
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "advapi32.lib")
or
#pragma comment(lib, "coredll.lib")
Since <boost/config/auto_link.hpp> seems to be oriented for various logics for linking boost libs and those 3 are not boost libs.
Didn't want to go to change that big myself, so implemented one that still uses auto_link.hpp but solves the problem.
This fixes #94
=> Fixes https://github.com/boostorg/uuid/issues/94

include/boost/uuid/detail/random_provider_detect_platform.hpp
Since getentropy is implemented via getrandom in Linux kernel, getentropy
cannot work if the kernel doesn't support getrandom. Given this, there is
no reason to ever use getentropy on Linux.
We used to allow this backend based on glibc version check, but there are
configurations where a newer glibc is running with an older kernel, and
getentropy always fails in runtime. Disabling getentropy in such cases
allows to fall back to the generic POSIX backend.
References https://github.com/boostorg/uuid/issues/92#issuecomment-479380506.
This fixes #92
=> Disable getentropy backend on Linux and Android

include/boost/uuid/uuid_hash.hpp
Not only it makes the two implementations equivalent, it also fixes the bug
of to_string throwing an exception in the noexcept function. It is also
more efficient as there is no need for the temporary string construction.
Alternative to https://github.com/boostorg/uuid/pull/99.
=> Implement std::hash in terms of hash_value.

.travis.yml, appveyor.yml
This adds some new compilers and reduces the overall workload of the CI by cutting back the number of cxxstd and variant combinations in total.
- Add Visual Studio 2019 on AppVeyor
- Add gcc-9 on Travis
- Reduce the cxxstd matrix to 2 choices on most Travis CI jobs
- Build mostly release variant with a few debug variants sprinkled in
- Disable cppcheck builds as they are hanging on some repositories
=> Improvements to CI

doc/uuid.html, include/boost/uuid/uuid_io.hpp, test/test_io.cpp
This is in particular useful for when allocating a std::string is too expensive.
=> Add to_chars for writing uuid strings without allocating

test/Jamfile.v2
Referring to `BOOST_ROOT` for dependencies is bad; if "b2 headers" had not been run yet at the top level and you tried to build uuid separately, the test jamfile was wrong.  With this fix it can build independently and seed the appropriate headers without a full build.
Without:
```
Performing configuration checks
- default address-model    : 64-bit [1]
- default architecture     : x86 [1]
- symlinks supported       : yes
error: Unable to find file or target named
error:     '/boost/boost/uuid/uuid.hpp'
error: referred to from project at
error:     'test'
```
=> fix test jamfile referring to BOOST_ROOT instead of relative paths

include/boost/uuid/detail/config.hpp, include/boost/uuid/detail/uuid_x86.ipp, test/test_msvc_simd_bug981648.hpp, test/test_msvc_simd_bug981648_foo.cpp, test/test_msvc_simd_bug981648_main.cpp
Prefer `vmovdqu` to `vlddqu` on CPUs supporting AVX. `vlddqu` has one extra cycle latency on Skylake and later Intel CPUs and is not merged to the following instructions as a memory operand, which makes the code slightly larger. Legacy SSE3 `lddqu` is still preferred because it is faster on Prescott and the same as `movdqu` on AMD CPUs. It also doesn't affect code size because `movdqu` cannot be converted to a memory operand as memory operands are required to be aligned in SSE.
Closes https://github.com/boostorg/uuid/issues/137.
Also, re-format the test code for MSVC bug 981648, no functional changes.
=> Improve generated x86 code for AVX targets

include/boost/uuid/uuid.hpp
The SSE-optimized routines are faster than `uint128_t`-based ones. Based on my tests on i7 12700K, with gcc 11.4, SSE4 `operator==` is 13% faster and `operator<` is 8% faster.
See the attached benchmark:
[uuid_operators2.cpp.gz](https://github.com/boostorg/uuid/files/15082637/uuid_operators2.cpp.gz)
Compiler command line:
```
g++ -I. -std=gnu++17 -O3 -march=nehalem -o uuid_operators2 uuid_operators2.cpp
```
Test output on my machine:
```
equal_uint128: Duration: 64.463747 ms, 1551259500.940893 calls per second, 23670.341506 MiB/s
less_uint128: Duration: 89.332442 ms, 1119414154.154658 calls per second, 17080.904452 MiB/s
equal_x86: Duration: 56.973550 ms, 1755200439.502190 calls per second, 26782.233269 MiB/s
less_x86: Duration: 82.242024 ms, 1215923382.430374 calls per second, …
```
=> Use SSE2 implementation when `uint128_t` is available

doc/uuid/configuration.adoc, include/boost/uuid/detail/config.hpp, include/boost/uuid/detail/uuid_x86.ipp
The new implementation offers about 20% speed improvement over the SSE2 version on i7 12700K, and about 30% over the `uint128_t`-based version.
Also added GitHub CI jobs with AVX-512 enabled to test the new implementation.
=> Add AVX-512/AVX10.1 implementation of `operator<`/`operator<=>`

include/boost/uuid/uuid.hpp
The includes are added for the `std::chrono` and `std::memcpy` that are explicitly mentioned in `uuid.hpp`.
=> Add missing includes

include/boost/uuid/detail/to_chars.hpp, include/boost/uuid/uuid.hpp
These are some more errors I'm seeing in the Unordered tests in [unordered#274](https://github.com/boostorg/unordered/pull/274). This is related to #162 / #163.
I reproduced it locally with GCC 9 with the command used in the CI.
```
"g++-9"   -std=c++11 -fvisibility-inlines-hidden -fPIC -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -Wextra -pedantic -Werror -fvisibility=hidden -Wconversion -Wfloat-equal -Wno-variadic-macros -Wshadow -Wsign-conversion -Wsign-promo -DBOOST_ALL_NO_LIB=1 -DNDEBUG   -I"."  -c -o "bin.v2/libs/unordered/test/visualization_tests.test/gcc-9/release/x86_64/cxxstd-11-iso/threading-multi/visibility-hidden/visualization_tests.o" "libs/unordered/test/debuggability/visualization_tests.cpp"
```
Here is a modification of the command that produces the same error …
=> Fix more sign conversion errors

include/boost/uuid/uuid.hpp
Failure seen in [unordered#274](https://github.com/boostorg/unordered/pull/274)
[CE link](https://godbolt.org/z/dcYes3PTc)
=> Fix missing-field-initializers error in GCC 4.8 and 4.9

CMakeLists.txt
CLANGARM64 does not have libatomic, disable it
=> fix: Disable libatomic link for windows arm64
